// [
//   {
//       "sch_id": "SCHMATE/117209",
//       "campus": "Corona Elementary",
//       "session": "2024/2025",
//       "student": "Jobs Steven",
//       "student_id": "17",
//       "assignment_id": "45",
//       "question_type": "theory",
//       "question": "Identify and explain the difference between a simile and a metaphor, providing examples of each.",
//       "question_number": "1",
//       "answer": "A simile is a figure of speech that directly compares two different things using \"like\" or \"as.\" For example, \"Her eyes sparkled like diamonds.\" On the other hand, a metaphor also compares two different things but does so by stating that one thing is anot",
//       "subject": "English Language",
//       "subject_id": "2",
//       "correct_answer": "A simile is a figure of speech that directly compares two different things using \"like\" or \"as.\" For example, \"Her eyes sparkled like diamonds.\" On the other hand, a metaphor also compares two different things but does so by stating that one thing is anot",
//       "mark": "not marked",
//       "submitted": "true",
//       "total_question": "0",
//       "question_mark": "3",
//       "total_mark": "3",
//       "week": "5",
//       "id": "33"
//   },
//   {
//       "sch_id": "SCHMATE/117209",
//       "campus": "Corona Elementary",
//       "session": "2024/2025",
//       "student": "Jobs Steven",
//       "student_id": "17",
//       "assignment_id": "46",
//       "question_type": "theory",
//       "question": "Define a compound word and provide three examples.",
//       "question_number": "2",
//       "answer": "A compound word is formed when two or more words are joined together to create a new word with a distinct meaning. Examples of compound words include \"sunflower,\" \"rainbow,\" and \"toothbrush.\"",
//       "subject": "English Language",
//       "subject_id": "2",
//       "correct_answer": "A compound word is formed when two or more words are joined together to create a new word with a distinct meaning. Examples of compound words include \"sunflower,\" \"rainbow,\" and \"toothbrush.\" In each case, two separate words are combined to form a single ",
//       "mark": "not marked",
//       "submitted": "true",
//       "total_question": "0",
//       "question_mark": "2",
//       "total_mark": "5",
//       "week": "5",
//       "id": "34"
//   }
// ]


// [
//   {
//       "sch_id": "SCHMATE/117209",
//       "campus": "Corona Elementary",
//       "period": "First Half",
//       "term": "First Term",
//       "session": "2024/2025",
//       "student_id": "17",
//       "subject_id": "2",
//       "assignment_id": "45",
//       "question_type": "theory",
//       "question": "Identify and explain the difference between a simile and a metaphor, providing examples of each.",
//       "question_number": "1",
//       "answer": "A simile is a figure of speech that directly compares two different things using \"like\" or \"as.\" For example, \"Her eyes sparkled like diamonds.\" On the other hand, a metaphor also compares two different things but does so by stating that one thing is anot",
//       "correct_answer": "A simile is a figure of speech that directly compares two different things using \"like\" or \"as.\" For example, \"Her eyes sparkled like diamonds.\" On the other hand, a metaphor also compares two different things but does so by stating that one thing is anot",
//       "submitted": "true",
//       "mark": "marked",
//       "teacher_mark": "2",
//       "total_question": "0",
//       "question_mark": "3",
//       "total_mark": "3",
//       "week": "5",
//       "id": "13"
//   },
//   {
//       "sch_id": "SCHMATE/117209",
//       "campus": "Corona Elementary",
//       "period": "First Half",
//       "term": "First Term",
//       "session": "2024/2025",
//       "student_id": "17",
//       "subject_id": "2",
//       "assignment_id": "46",
//       "question_type": "theory",
//       "question": "Define a compound word and provide three examples.",
//       "question_number": "2",
//       "answer": "A compound word is formed when two or more words are joined together to create a new word with a distinct meaning. Examples of compound words include \"sunflower,\" \"rainbow,\" and \"toothbrush.\"",
//       "correct_answer": "A compound word is formed when two or more words are joined together to create a new word with a distinct meaning. Examples of compound words include \"sunflower,\" \"rainbow,\" and \"toothbrush.\" In each case, two separate words are combined to form a single",
//       "submitted": "true",
//       "mark": "marked",
//       "teacher_mark": "2",
//       "total_question": "0",
//       "question_mark": "2",
//       "total_mark": "5",
//       "week": "5",
//       "id": "14"
//   }
// ]