on:
    push:
      branches:
        - dev
name: 🚀 Deploy to staging
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-24.04
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build --verbose
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: cloud102.hostgator.com
        username: ${{ secrets.staging_username }}
        password: ${{ secrets.staging_password }}

